{
    'name': "App One",
    'author': "Mohamed Atef",
    'category': '',
    'version': '17.0.0.1',
    'depends': ['base','sale_management','account','mail','stock','purchase',
                ],
    'data': [   
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/sequance.xml',
        'views/base_menu.xml',
        'views/property_view.xml',
        'views/owner_view.xml',
        'views/tag.xml',
        'views/sale_order.xml',
        'views/res.partner.xml',
        'views/vendor_list_view.xml',
        'views/vendor_form_view.xml',
        'views/vendor_kanban_view.xml',
        'views/vendor_search_view.xml',
        'views/products.xml',
        'views/building.xml',
        'views/account_move.xml',
        'views/purchase_order.xml',
        'views/res_users.xml',
        'reports/porperty_report.xml',
        'reports/sales_report_templete.xml',
        'reports/sales_reports.xml',
        'views/property_history.xml',
        'views/stages.xml',
        'views/collection_report_views.xml',
        'wizard/change_state_wizard_view.xml',
    ],
    'assets' : {
        'web.assets_backend' : [
            'app_one/static/src/css/property.css',
            'app_one/static/src/components/listView/listView.css',
            'app_one/static/src/components/listView/listView.js',
            'app_one/static/src/components/listView/listView.xml',
            'app_one/static/src/components/salesOwl/saleOwl.css',
            'app_one/static/src/components/salesOwl/saleOwl.js',
            'app_one/static/src/components/salesOwl/saleOwl.xml',
            # 'app_one/static/src/components/formView/formView.css',
            'app_one/static/src/components/formView/formView.js',
            'app_one/static/src/components/formView/formView.xml',

                                ],
        'web.report_assets_common': ['app_one/static/src/css/font.css'],


    },
    'application': True,
}

